-- Clean-install model. Scope: APP_DEMO_IDEM B2B Order Forensics only.
create table bf_customer (
 customer_id number generated by default on null as identity,
 customer_code varchar2(30 char) not null,
 customer_name varchar2(200 char) not null,
 constraint bf_customer_pk primary key(customer_id),
 constraint bf_customer_code_uq unique(customer_code)
);
create table bf_product (
 product_id number generated by default on null as identity,
 sku varchar2(40 char) not null,
 product_name varchar2(200 char) not null,
 brand varchar2(40 char) not null,
 category varchar2(40 char) not null,
 description varchar2(400 char) not null,
 artwork_key varchar2(20 char) not null,
 unit_price number(12,2) not null,
 active_flag char(1) default 'Y' not null,
 constraint bf_product_pk primary key(product_id),
 constraint bf_product_sku_uq unique(sku),
 constraint bf_product_price_ck check(unit_price>0),
 constraint bf_product_active_ck check(active_flag in ('Y','N'))
);
create table bf_order_intent (
 request_hash varchar2(64 char) not null,
 customer_id number not null,
 request_json clob not null,
 app_user varchar2(255 char) not null,
 apex_session_id varchar2(64 char) not null,
 created_at timestamp with local time zone default systimestamp not null,
 constraint bf_intent_pk primary key(request_hash),
 constraint bf_intent_customer_fk foreign key(customer_id) references bf_customer(customer_id),
 constraint bf_intent_json_ck check(request_json is json)
);
create table bf_order (
 order_id number generated by default on null as identity,
 order_number varchar2(40 char) not null,
 customer_id number not null,
 request_hash varchar2(64 char) not null,
 attempt_no number not null,
 status varchar2(20 char) default 'RECEIVED' not null,
 total_amount number(14,2) default 0 not null,
 delivery_service varchar2(30 char),
 delivery_account varchar2(64 char),
 created_by varchar2(255 char) not null,
 created_at timestamp with local time zone default systimestamp not null,
 updated_at timestamp with local time zone default systimestamp not null,
 checkout_at timestamp with local time zone,
 apex_session_id varchar2(64 char) not null,
 correlation_id varchar2(64 char) not null,
 constraint bf_order_pk primary key(order_id),
 constraint bf_order_number_uq unique(order_number),
 constraint bf_order_customer_fk foreign key(customer_id) references bf_customer(customer_id),
 constraint bf_order_intent_fk foreign key(request_hash) references bf_order_intent(request_hash),
 constraint bf_order_attempt_uq unique(request_hash,attempt_no),
 constraint bf_order_intention_uq unique(request_hash),
 constraint bf_order_status_ck check(status in ('RECEIVED','PROCESSING','COMPLETED','ERROR')),
 constraint bf_order_amount_ck check(total_amount>=0)
);
create index bf_order_customer_ix on bf_order(customer_id,created_at);
create index bf_order_correlation_ix on bf_order(correlation_id);
create index bf_order_session_ix on bf_order(apex_session_id);
create table bf_order_item (
 order_item_id number generated by default on null as identity,
 order_id number not null,
 product_id number not null,
 line_number number not null,
 product_name varchar2(200 char) not null,
 quantity number(6) not null,
 unit_price number(12,2) not null,
 line_total number generated always as (quantity*unit_price) virtual,
 constraint bf_order_item_pk primary key(order_item_id),
 constraint bf_order_item_order_fk foreign key(order_id) references bf_order(order_id),
 constraint bf_order_item_product_fk foreign key(product_id) references bf_product(product_id),
 constraint bf_order_item_line_uq unique(order_id,line_number),
 constraint bf_order_item_qty_ck check(quantity between 1 and 99),
 constraint bf_order_item_price_ck check(unit_price>0)
);
create index bf_order_item_product_ix on bf_order_item(product_id);
create table bf_lab_config (
 config_id number primary key,
 selection_mode varchar2(30 char) default 'RANDOM' not null,
 constraint bf_lab_singleton_ck check(config_id=1),
 constraint bf_lab_mode_ck check(selection_mode in ('RANDOM','CLEAN','OVERFLOW','PRE_INTEGRATION','RETRY'))
);
create table bf_lab_assignment (
 request_hash varchar2(64 char) primary key,
 scenario varchar2(30 char) not null,
 created_at timestamp with local time zone default systimestamp not null,
 constraint bf_lab_intent_fk foreign key(request_hash) references bf_order_intent(request_hash),
 constraint bf_lab_case_ck check(scenario in ('CLEAN','OVERFLOW','PRE_INTEGRATION','RETRY'))
);
create table bf_integration_log (
  integration_log_id number generated always as identity,
  event_at           timestamp with local time zone default systimestamp not null,
  endpoint           varchar2(500 char) not null,
  http_status        number,
  business_code      varchar2(60 char),
  business_message   varchar2(2000 char),
  payload_hash       varchar2(64 char),
  response_excerpt   varchar2(4000 char),
  correlation_id     varchar2(64 char) not null,
  order_id           number,
  apex_session_id    varchar2(64 char),
  constraint bf_integration_log_pk primary key (integration_log_id)
);

create index bf_integration_corr_ix on bf_integration_log (correlation_id, event_at);
create index bf_integration_order_ix on bf_integration_log (order_id, event_at);

create table bf_access_log (
  access_log_id      number generated always as identity,
  event_at           timestamp with local time zone default systimestamp not null,
  application_id     number,
  page_id            number,
  apex_session_id    varchar2(64 char),
  request_value      varchar2(255 char),
  app_user           varchar2(255 char),
  request_url        varchar2(2000 char),
  correlation_id     varchar2(64 char),
  order_id           number,
  constraint bf_access_log_pk primary key (access_log_id)
);

create index bf_access_corr_ix on bf_access_log (correlation_id, event_at);
create index bf_access_order_ix on bf_access_log (order_id, event_at);

create table bf_error_log (
  error_log_id       number generated always as identity,
  event_at           timestamp with local time zone default systimestamp not null,
  sql_code           number,
  sql_error_message  varchar2(4000 char),
  error_stack        clob,
  error_backtrace    clob,
  page_id            number,
  action_name        varchar2(255 char),
  apex_session_id    varchar2(64 char),
  order_id           number,
  correlation_id     varchar2(64 char),
  constraint bf_error_log_pk primary key (error_log_id)
);

create index bf_error_corr_ix on bf_error_log (correlation_id, event_at);
create index bf_error_order_ix on bf_error_log (order_id, event_at);

create table bf_debug_event (
  debug_event_id     number generated always as identity,
  event_at           timestamp with local time zone default systimestamp not null,
  log_level          varchar2(10 char) default 'INFO' not null,
  component_name     varchar2(255 char) not null,
  message_text       varchar2(4000 char) not null,
  context_json       clob,
  apex_session_id    varchar2(64 char),
  correlation_id     varchar2(64 char),
  order_id           number,
  constraint bf_debug_event_pk primary key (debug_event_id),
  constraint bf_debug_level_ck check (log_level in ('TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR')),
  constraint bf_debug_json_ck check (context_json is json)
);

create index bf_debug_corr_ix on bf_debug_event (correlation_id, event_at);
create index bf_debug_order_ix on bf_debug_event (order_id, event_at);

-- Separate transport attempts from the single business order.
create table bf_submission_attempt (
 attempt_id number generated always as identity primary key,
 request_hash varchar2(64 char) not null references bf_order_intent(request_hash),
 order_id number not null references bf_order(order_id),
 correlation_id varchar2(64 char) not null unique,
 received_at timestamp with time zone default systimestamp not null,
 outcome varchar2(20 char) not null check(outcome in ('CREATED','REPLAY')),
 app_user varchar2(255 char) not null,
 apex_session_id varchar2(64 char) not null
);
create index bf_submission_intent_ix on bf_submission_attempt(request_hash,received_at);
create table bf_app_config (
 config_id number primary key check(config_id=1),
 application_id number not null unique
);
